
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 13 12:01:11 ECT 2022
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLY = 14;
  public static final int QUOTES = 16;
  public static final int WHILE = 9;
  public static final int POPEN = 17;
  public static final int IDENTIFIER = 25;
  public static final int ERROR = 28;
  public static final int TRUE = 26;
  public static final int COMPARATOR = 22;
  public static final int SUBTRACT = 13;
  public static final int EOL = 21;
  public static final int RETURNC = 10;
  public static final int STRING = 4;
  public static final int WOPEN = 19;
  public static final int FLOAT = 3;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int ADD = 12;
  public static final int FALSE = 27;
  public static final int WCLOSE = 20;
  public static final int PRINT = 6;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int IFC = 7;
  public static final int PCLOSE = 18;
  public static final int INTEGER = 2;
  public static final int ELSEC = 8;
  public static final int VOID = 5;
  public static final int NFLOAT = 24;
}

