
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 28 19:24:54 ECT 2022
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLY = 13;
  public static final int QUOTES = 15;
  public static final int POPEN = 16;
  public static final int IDENTIFIER = 24;
  public static final int ERROR = 25;
  public static final int COMPARATOR = 21;
  public static final int SUBTRACT = 12;
  public static final int EOL = 20;
  public static final int RETURNC = 9;
  public static final int STRING = 4;
  public static final int WOPEN = 18;
  public static final int FLOAT = 3;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 14;
  public static final int ADD = 11;
  public static final int WCLOSE = 19;
  public static final int PRINT = 6;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int IFC = 7;
  public static final int PCLOSE = 17;
  public static final int INTEGER = 2;
  public static final int ELSEC = 8;
  public static final int VOID = 5;
  public static final int NFLOAT = 23;
}

